import { MenuItem } from "@/types";
import {
  Cake,
  ChefHat,
  Coffee,
  Globe,
  UtensilsCrossed,
  Wine,
} from "lucide-react";

export const menuItems: MenuItem[] = [
  {
    id: "app-1",
    name: "Crispy Calamari",
    description:
      "Lightly fried squid rings served with spicy marinara sauce and lemon aioli",
    price: 14.99,
    category: "Appetizers",
    subCategory: "Seafood",
    tags: ["seafood", "fried"],
    popular: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "app-2",
    name: "Bruschetta Classica",
    description:
      "Toasted artisan bread topped with fresh tomatoes, garlic, basil, and balsamic glaze",
    price: 9.99,
    category: "Appetizers",
    subCategory: "Vegetarian",
    tags: ["vegetarian", "italian"],
    veg: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "app-3",
    name: "Spicy Chicken Wings",
    description:
      "Jumbo wings tossed in house-made buffalo sauce, served with blue cheese dip",
    price: 13.99,
    category: "Appetizers",
    subCategory: "Chicken",
    tags: ["chicken", "spicy"],
    spicy: true,
    popular: true,
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "app-4",
    name: "Spring Rolls",
    description:
      "Crispy rolls filled with glass noodles, vegetables, and choice of chicken or tofu",
    price: 8.99,
    category: "Appetizers",
    subCategory: "Asian",
    tags: ["asian", "crispy"],
    veg: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "afr-1",
    name: "Jollof Rice with Chicken",
    description:
      "West African spiced tomato rice with grilled chicken, plantains, and coleslaw",
    price: 18.99,
    category: "African Specialties",
    subCategory: "West African",
    tags: ["west african", "rice", "popular"],
    popular: true,
    spicy: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "afr-2",
    name: "Egusi Soup with Pounded Yam",
    description:
      "Rich melon seed soup with assorted meat, fish, and leafy vegetables",
    price: 19.99,
    category: "African Specialties",
    subCategory: "West African",
    tags: ["soup", "traditional", "nigeria"],
    spicy: true,
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "afr-3",
    name: "Suya Platter",
    description:
      "Spicy grilled beef skewers with onions, tomatoes, and extra yaji spice",
    price: 16.99,
    category: "African Specialties",
    subCategory: "Street Food",
    tags: ["grilled", "spicy", "street food"],
    spicy: true,
    popular: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "afr-4",
    name: "Doro Wat",
    description:
      "Ethiopian spicy chicken stew with berbere spice and hard-boiled eggs, served with injera",
    price: 21.99,
    category: "African Specialties",
    subCategory: "East African",
    tags: ["ethiopian", "stew", "spicy"],
    spicy: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "int-1",
    name: "Grilled Ribeye Steak",
    description:
      "14oz prime ribeye grilled to perfection, served with garlic mash and seasonal vegetables",
    price: 34.99,
    category: "Intercontinental",
    subCategory: "Steakhouse",
    tags: ["steak", "premium"],
    popular: true,
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "int-2",
    name: "Miso Glazed Salmon",
    description:
      "Norwegian salmon with sweet miso glaze, jasmine rice, and bok choy",
    price: 27.99,
    category: "Intercontinental",
    subCategory: "Seafood",
    tags: ["seafood", "japanese", "healthy"],
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "int-3",
    name: "Chicken Alfredo Pasta",
    description:
      "Fettuccine in creamy parmesan sauce with grilled chicken and fresh parsley",
    price: 19.99,
    category: "Intercontinental",
    subCategory: "Italian",
    tags: ["pasta", "italian", "creamy"],
    popular: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "int-4",
    name: "Vegetable Pad Thai",
    description:
      "Rice noodles stir-fried with tofu, bean sprouts, peanuts, and tamarind sauce",
    price: 16.99,
    category: "Intercontinental",
    subCategory: "Asian",
    tags: ["thai", "noodles", "vegetarian"],
    veg: true,
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "int-5",
    name: "Beef Burger Deluxe",
    description:
      "Angus beef patty, aged cheddar, caramelized onions, lettuce, tomato, and house sauce",
    price: 17.99,
    category: "Intercontinental",
    subCategory: "American",
    tags: ["burger", "american", "classic"],
    popular: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "des-1",
    name: "Molten Chocolate Cake",
    description:
      "Warm chocolate cake with liquid center, served with vanilla ice cream",
    price: 9.99,
    category: "Desserts",
    subCategory: "Cakes",
    tags: ["chocolate", "warm", "ice cream"],
    popular: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "des-2",
    name: "Cheesecake New York Style",
    description: "Creamy cheesecake with graham cracker crust and berry coulis",
    price: 8.99,
    category: "Desserts",
    subCategory: "Cakes",
    tags: ["cheesecake", "creamy"],
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "des-3",
    name: "Puff-Puff",
    description:
      "Nigerian fried dough balls dusted with powdered sugar and cinnamon",
    price: 6.99,
    category: "Desserts",
    subCategory: "African",
    tags: ["african", "fried", "sweet"],
    popular: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "des-4",
    name: "Tiramisu",
    description:
      "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone cream",
    price: 8.99,
    category: "Desserts",
    subCategory: "Italian",
    tags: ["italian", "coffee", "creamy"],
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "drk-1",
    name: "Fresh Lemonade",
    description: "House-made with fresh lemons, mint, and a touch of honey",
    price: 4.99,
    category: "Drinks",
    subCategory: "Non-Alcoholic",
    tags: ["refreshing", "non-alcoholic"],
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "drk-2",
    name: "Zobo Drink",
    description: "Traditional Nigerian hibiscus tea with ginger and pineapple",
    price: 4.99,
    category: "Drinks",
    subCategory: "Non-Alcoholic",
    tags: ["african", "hibiscus", "traditional"],
    popular: true,
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "drk-3",
    name: "Chapman Cocktail",
    description:
      "Nigerian classic cocktail with grenadine, sprite, and fresh fruits",
    price: 7.99,
    category: "Drinks",
    subCategory: "Cocktails",
    tags: ["cocktail", "african", "fruity"],
    popular: true,
    image: "/assets/homeImg2.jpg",
  },
  {
    id: "drk-4",
    name: "House Red Wine",
    description: "Full-bodied cabernet sauvignon from South Africa",
    price: 8.99,
    category: "Drinks",
    subCategory: "Wine",
    tags: ["wine", "red"],
    image: "/assets/homeImg3.jpg",
  },
  {
    id: "drk-5",
    name: "Espresso Martini",
    description: "Vodka, fresh espresso, coffee liqueur, and simple syrup",
    price: 11.99,
    category: "Drinks",
    subCategory: "Cocktails",
    tags: ["cocktail", "coffee"],
    image: "/assets/homeImg1.jpg",
  },
  {
    id: "drk-6",
    name: "Smoothie Bowl",
    description:
      "Acai berry blend topped with granola, banana, and coconut flakes",
    price: 8.99,
    category: "Drinks",
    subCategory: "Smoothies",
    tags: ["healthy", "breakfast", "vegan"],
    veg: true,
    image: "/assets/homeImg2.jpg",
  },
];

export const categories = [
  { id: "all", name: "All", icon: UtensilsCrossed },
  { id: "Appetizers", name: "Appetizers", icon: Coffee },
  { id: "African Specialties", name: "African", icon: Globe },
  { id: "Intercontinental", name: "Global", icon: ChefHat },
  { id: "Desserts", name: "Desserts", icon: Cake },
  { id: "Drinks", name: "Drinks", icon: Wine },
];

export const featuredItems = menuItems
  .filter((item) => item.popular)
  .slice(0, 6);
